### ISSUE TITLE
retools 0.4 install broken / missing CHANGES.rst

### ISSUE THREAD

**Issue by mandarjog** [bbangert/retools#23]
[~/plotwatt/crons] # pip install retools
Downloading/unpacking retools
  Running setup.py egg_info for package retools
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/home/ubuntu/PWPYTHON/build/retools/setup.py", line 9, in <module>
        CHANGES = open(os.path.join(here, 'CHANGES.rst')).read()
    IOError: [Errno 2] No such file or directory: '/home/ubuntu/PWPYTHON/build/retools/CHANGES.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/home/ubuntu/PWPYTHON/build/retools/setup.py", line 9, in <module>

```
CHANGES = open(os.path.join(here, 'CHANGES.rst')).read()
```

IOError: [Errno 2] No such file or directory: '/home/ubuntu/PWPYTHON/build/retools/CHANGES.rst'

---

Command python setup.py egg_info failed with error code 1 in /home/ubuntu/PWPYTHON/build/retools
Storing complete log in /home/ubuntu/.pip/pip.log

**Comment by bbangert** [comment]
This was fixed and now includes the changes file.
