### ISSUE TITLE
AttributeError: 'Worker' object has no attribute 'serializer'

### ISSUE THREAD

**Issue by jayd3e** [bbangert/retools#29]
Running a worker yields this error right now:

```
Traceback (most recent call last):
  File "/app/.heroku/python/bin/clusterworker", line 9, in <module>
    load_entry_point('clustercourses==0.0.25', 'console_scripts', 'clusterworker')()
  File "/app/.heroku/src/clusterapp/clusterapp/__init__.py", line 139, in worker
    blocking=args.blocking)
  File "/app/.heroku/python/lib/python2.7/site-packages/retools/queue.py", line 459, in work
    if not self.paused and self.reserve(interval, blocking):
  File "/app/.heroku/python/lib/python2.7/site-packages/retools/queue.py", line 505, in reserve
    redis=self.redis, serializer=self.serializer,
AttributeError: 'Worker' object has no attribute 'serializer'
```

And it's in the current 0.4.1 version on pypi.

**Comment by msabramo** [comment]
This issue was fixed by https://github.com/bbangert/retools/commit/3d41f87855f6bf21bba1d2410fd8bea895567ece (PR #30) so I think it can be closed.

@bbangert: Are you able to do a release to PyPI? Because, as @jayd3e mentioned, 0.4.1 is busted.

**Comment by msabramo** [comment]
Cc: @sontek :smile:
